/* Copyright(C) 2007 National Institute of Informatics, All rights reserved.*/
CREATE USER SA PASSWORD "" ADMIN

DROP TABLE PAYMENT IF EXISTS;
DROP TABLE AVAILABLEQTY IF EXISTS;
DROP TABLE RESERVATION IF EXISTS;
DROP TABLE ROOM IF EXISTS;

CREATE TABLE PAYMENT(ROOMNUMBER VARCHAR(50) NOT NULL,STAYINGDATE VARCHAR(20) NOT NULL,AMOUNT INTEGER,STATUS VARCHAR(10),CONSTRAINT ROOMNUMBER_STAYINGDATE PRIMARY KEY(ROOMNUMBER,STAYINGDATE));
CREATE TABLE AVAILABLEQTY(DATE VARCHAR(20) NOT NULL PRIMARY KEY,QTY INTEGER);
CREATE TABLE RESERVATION(RESERVATIONNUMBER VARCHAR(50) NOT NULL PRIMARY KEY,STAYINGDATE VARCHAR(20),STATUS VARCHAR(10),TYPE VARCHAR(10));
CREATE TABLE ROOM(ROOMNUMBER VARCHAR(50) NOT NULL PRIMARY KEY,STAYINGDATE VARCHAR(20),TYPE VARCHAR(10));

INSERT INTO ROOM VALUES('1001','', 'STANDARD');
INSERT INTO ROOM VALUES('1002','', 'STANDARD');
INSERT INTO ROOM VALUES('1003','', 'STANDARD');
INSERT INTO ROOM VALUES('1004','', 'STANDARD');
INSERT INTO ROOM VALUES('1005','', 'STANDARD');
INSERT INTO ROOM VALUES('2001','', 'SUITE');
INSERT INTO ROOM VALUES('2002','', 'SUITE');
